# Slug -> (cluster, heading-keys, title). heading-keys sind die Doc-Nummern.
# netzwerk-modell fasst 1.12 + 1.13 zusammen. K4 nutzt die "Überblick"-Nummer.
_RAW = [
    # K1 Grundlagen
    ("sag-mal-gunther", "k1", ["1.3s"], "Sag mal, Gunther …"),
    ("werdegang-wurzeln", "k1", ["1.3w"], "Werdegang & Wurzeln"),
    ("hypnosyst-denken", "k1", ["1.4"], "Hypnosystemisches Denken"),
    ("rollenverstaendnis", "k1", ["1.5"], "Hypnosystemisches Rollenverständnis"),
    ("haltung", "k1", ["1.6"], "Hypnosystemische Haltung"),
    ("hypnosystemischer-ansatz", "k1", ["1.7"], "Ansatz auf den Punkt"),
    ("angst", "k1", ["1.8"], "Praxisbeispiel Angst"),
    ("erleben-erzeugen", "k1", ["1.9"], "Wie erzeugen wir unser Erleben?"),
    ("hirnforschung", "k1", ["1.10"], "Erkenntnisse der Hirnforschung"),
    ("grundlagenmodell", "k1", ["1.11"], "Elementares Grundlagenmodell"),
    ("netzwerk-modell", "k1", ["1.12", "1.13"], "Netzwerk-Modell"),
    ("trance-transparenz", "k1", ["1.14"], "Trance & Transparenz"),
    ("selbsterfahrung", "k1", ["1.15"], "Selbsterfahrung"),
    ("probleme-basteln", "k1", ["1.16"], "Bastelanleitung für Probleme"),
    ("potenzialhypothese", "k1", ["1.17"], "Potenzialhypothese"),
    # K2 Herausforderungen
    ("ursachen", "k2", ["2.1"], "Bedeutung von Ursachen"),
    ("symptomverstaendnis", "k2", ["2.2"], "Symptomverständnis"),
    ("neutralitaet", "k2", ["2.3"], "Neutralität"),
    ("abgrenzung", "k2", ["2.4"], "Abgrenzungsfähigkeit"),
    ("diagnosen", "k2", ["2.5"], "Diagnosen"),
    ("burnout", "k2", ["2.6"], "Burnout"),
    ("entscheidungen", "k2", ["2.7"], "Entscheidungssituationen"),
    ("restriktionen", "k2", ["2.8"], "Umgang mit Restriktionen"),
    ("versoehnung", "k2", ["2.9"], "Das Konzept der Versöhnung"),
    ("loesung-aller-probleme", "k2", ["2.10"], "Die Lösung aller Probleme"),
    # K3 Handwerk
    ("beratungssystem", "k3", ["3.1.2"], "Beratungssystem & Utilisationsansatz"),
    ("zuweisungsdynamik", "k3", ["3.1.3"], "Klärung der Zuweisungs-Dynamik"),
    ("auftragsklaerung", "k3", ["3.1.4"], "Auftragsklärung"),
    ("unterschiede", "k3", ["3.1.5"], "Fokus auf Unterschiede"),
    ("utilisation", "k3", ["3.1.6"], "Utilisation von Unterschieden"),
    ("steuerposition", "k3", ["3.1.7"], "Aufbau einer Steuerposition"),
    ("interventionen", "k3", ["3.1.8"], "Weitere Interventionen"),
    ("utilisation-problemsituationen", "k3", ["3.1.9"], "Utilisation von Problemsituationen"),
    ("utilisation-ambivalenzen", "k3", ["3.1.10"], "Utilisation von Ambivalenzen"),
    ("utilisation-rueckfaelle", "k3", ["3.1.11"], "Utilisation von Rückfällen"),
    ("abschluss-transfer", "k3", ["3.1.12"], "Abschluss & Transfer"),
    ("fallanalyse-ungewisses", "k3", ["3.2"], "Fallanalyse: Umgang mit dem Ungewissen"),
    ("selbstfuersorge", "k3", ["3.3.2"], "Selbstfürsorge"),
    ("eigene-wahrgebung", "k3", ["3.3.3"], "Utilisation der eigenen „Wahrgebung“"),
    ("zugang-kompetenzen", "k3", ["3.3.4"], "Optimaler Zugang zu Kompetenzen"),
    ("imagination-steuerposition", "k3", ["3.3.5"], "Imagination: Steuerposition"),
    ("innere-weisheit", "k3", ["3.3.6"], "Imagination: Innere Weisheit"),
    # K4 Praxisfälle (Text = Überblick)
    ("depression", "k4", ["4.2.4"], "Depressionen"),
    ("trauer-schuld", "k4", ["4.3.3"], "Trauer & Schuld"),
    ("schmerzen", "k4", ["4.4.4"], "Chronische Schmerzen"),
    ("panik", "k4", ["4.5.4"], "Panikattacken"),
    ("paarkonflikt", "k4", ["4.6.3"], "Paarkonflikt"),
    ("trauma", "k4", ["4.7.4"], "Trauma"),
    ("sucht", "k4", ["4.8.4"], "Alkohol- und Nikotinsucht"),
    ("essverhalten", "k4", ["4.9.2"], "Ess- und Bewegungsgewohnheiten"),
]
NODES = [{"slug": s, "cluster": c, "headings": h, "title": t} for (s, c, h, t) in _RAW]
BY_SLUG = {n["slug"]: n for n in NODES}
