# scripts/nmds-layout/psyche_manifest.py
# Kuratierte Bischof-Konzepte. headings = laufende Nummer (Ordner <seq>-<slug>).
# terms = Retrieval-Suchbegriffe (Task 4). Cluster p1..p5 (siehe spaces.py).
_RAW = [
    # (slug, cluster, seq, title, terms)
    ('objektivierung', 'p1', '1', 'Objektivierung', ['Objektivierung', 'Objektivität', 'Veridikalität', 'wissenschaftliche Psychologie', 'Naturwissenschaft']),
    ('leib-seele-problem', 'p1', '2', 'Leib-Seele-Problem', ['Leib-Seele', 'Dualismus', 'Bewusstsein', 'Materialismus', 'Monismus']),
    ('teleologie-finalitaet', 'p1', '3', 'Teleologie und Finalität', ['Teleologie', 'Finalität', 'Zweck', 'Funktion', 'Vitalismus']),
    ('kausalitaet-erklaerung', 'p1', '4', 'Kausalität und Erklärung', ['Kausalität', 'Ursache', 'Erklärung', 'Determinismus', 'Mechanismus']),
    ('reduktionismus', 'p1', '5', 'Reduktionismus', ['Reduktion', 'Reduktionismus', 'Emergenz', 'Vitalismus', 'Naturwissenschaft']),
    ('erkennen-wirklichkeit', 'p1', '6', 'Erkennen und Wirklichkeit', ['Erkennen', 'Erkenntnis', 'Wirklichkeit', 'Realität', 'Wahrheit']),
    ('theoriebildung-methode', 'p1', '7', 'Theoriebildung und Methode', ['Theorie', 'Hypothese', 'Empirie', 'Konstrukt', 'Postulat']),
    ('behaviorismus', 'p1', '8', 'Behaviorismus', ['Behaviorismus', 'Reiz-Reaktion', 'Verhalten', 'Konditionierung', 'Reaktion']),
    ('phaenomenologie-introspektion', 'p1', '9', 'Phänomenologie und Introspektion', ['Phänomenologie', 'Erleben', 'Bewusstsein', 'Introspektion', 'Subjekt']),
    ('natur-vs-geisteswissenschaft', 'p1', '10', 'Erklären vs. Verstehen', ['Naturwissenschaft', 'Geisteswissenschaft', 'Verstehen', 'Erklären', 'Kausalität']),
    ('zuercher-modell', 'p2', '11', 'Zürcher Modell der sozialen Motivation', ['Zürcher Modell', 'soziale Motivation', 'Sicherheit', 'Erregung', 'Autonomie']),
    ('sicherheitssystem', 'p2', '12', 'Sicherheitssystem', ['Sicherheitssystem', 'Sicherheit', 'Geborgenheit', 'Vertrautheit', 'Bindung']),
    ('erregungssystem', 'p2', '13', 'Erregungssystem', ['Erregungssystem', 'Erregung', 'Neugier', 'Exploration', 'Fremdheit']),
    ('autonomiesystem', 'p2', '14', 'Autonomiesystem', ['Autonomiesystem', 'Autonomie', 'Rang', 'Dominanz', 'Prestige']),
    ('bindung-fuersorge', 'p2', '15', 'Bindung und Fürsorge', ['Bindung', 'Fürsorge', 'Geborgenheit', 'Abhängigkeit', 'Bindungssystem']),
    ('appetenz-aversion', 'p2', '16', 'Appetenz und Aversion', ['Appetenz', 'Aversion', 'Annäherung', 'Vermeidung', 'Valenz']),
    ('coping-bewaeltigung', 'p2', '17', 'Coping und Bewältigung', ['Coping', 'Bewältigung', 'Invention', 'Aggression', 'Supplikation']),
    ('praegung', 'p2', '18', 'Prägung', ['Prägung', 'Reifung', 'Ethologie', 'Instinkt', 'Ontogenese']),
    ('abloesung-individuation', 'p2', '19', 'Ablösung und Individuation', ['Ablösung', 'Adoleszenz', 'Autonomie', 'Abhängigkeit', 'Individuation']),
    ('dominanz-rang', 'p2', '20', 'Dominanz und Rang', ['Dominanz', 'Rang', 'Hierarchie', 'Macht', 'Imponieren']),
    ('sexualitaet-paarbindung', 'p2', '21', 'Sexualität und Paarbindung', ['Sexualität', 'Paarbindung', 'Inzest', 'Liebe', 'Bindung']),
    ('motiv-trieb-beduerfnis', 'p2', '22', 'Motiv, Trieb und Bedürfnis', ['Motivation', 'Motiv', 'Trieb', 'Bedürfnis', 'Antrieb']),
    ('wahrnehmung', 'p3', '23', 'Wahrnehmung', ['Wahrnehmung', 'Wahrnehmungspsychologie', 'Sinnesorgan', 'Reiz', 'Perzept']),
    ('gestalt', 'p3', '24', 'Gestalt', ['Gestalt', 'Gestaltpsychologie', 'Prägnanz', 'Ganzheit', 'Figur-Grund']),
    ('wahrnehmungskonstanz', 'p3', '25', 'Wahrnehmungskonstanz', ['Konstanz', 'Wahrnehmungskonstanz', 'Objekt', 'Veridikalität', 'Wahrnehmung']),
    ('aktualgenese', 'p3', '26', 'Aktualgenese', ['Aktualgenese', 'Wahrnehmung', 'Gestalt', 'Prägnanz', 'Erleben']),
    ('reafferenzprinzip', 'p3', '27', 'Reafferenzprinzip', ['Reafferenz', 'Reafferenzprinzip', 'Efferenzkopie', 'Afferenz', 'Efferenz']),
    ('bedeutung-sinn', 'p3', '28', 'Bedeutung und Sinn', ['Bedeutung', 'Sinn', 'Intentionalität', 'Bewusstsein', 'Vorstellung']),
    ('repraesentation-schema', 'p3', '29', 'Repräsentation und Schema', ['Repräsentation', 'Schema', 'Vorstellung', 'Erwartung', 'Antizipation']),
    ('denken-begriff', 'p3', '30', 'Denken und Begriff', ['Denken', 'Begriff', 'Abstraktion', 'Symbol', 'Kategorisierung']),
    ('sprache-zeichen', 'p3', '31', 'Sprache und Zeichen', ['Sprache', 'Zeichen', 'Symbol', 'Kommunikation', 'Begriff']),
    ('gedaechtnis-lernen', 'p3', '32', 'Gedächtnis und Lernen', ['Lernen', 'Gedächtnis', 'Assoziation', 'Erfahrung', 'Schema']),
    ('subjekt-objekt', 'p3', '33', 'Subjekt und Objekt', ['Subjekt', 'Objekt', 'Umwelt', 'Merkmal', 'Wahrnehmung']),
    ('emotion', 'p4', '34', 'Emotion', ['Emotion', 'Gefühl', 'Affekt', 'Stimmung', 'Bewertung']),
    ('affekt-stimmung', 'p4', '35', 'Affekt und Stimmung', ['Affekt', 'Stimmung', 'Aktivation', 'Aktivierung', 'Erregung']),
    ('lust-unlust-valenz', 'p4', '36', 'Lust, Unlust und Valenz', ['Lust', 'Unlust', 'Valenz', 'Wohlbefinden', 'Bewertung']),
    ('angst', 'p4', '37', 'Angst', ['Angst', 'Flucht', 'Vermeidung', 'Sicherheit', 'Aversion']),
    ('aggression', 'p4', '38', 'Aggression', ['Aggression', 'Flucht', 'Dominanz', 'Konflikt', 'Rivalität']),
    ('scham-schuld', 'p4', '39', 'Scham und Schuld', ['Scham', 'Schuld', 'Stolz', 'Demut', 'Prestige']),
    ('stress-frustration', 'p4', '40', 'Stress und Frustration', ['Stress', 'Frustration', 'Bewältigung', 'Konflikt', 'Belastung']),
    ('liebe-empathie', 'p4', '41', 'Liebe und Empathie', ['Liebe', 'Empathie', 'Fürsorge', 'Bindung', 'Attraktivität']),
    ('ambivalenz-konflikt', 'p4', '42', 'Ambivalenz und Konflikt', ['Konflikt', 'Ambivalenz', 'Annäherung', 'Vermeidung', 'Frustration']),
    ('systemtheorie-organismus', 'p5', '43', 'Systemtheorie und Organismus', ['Systemtheorie', 'System', 'Organismus', 'Ganzheit', 'Funktion']),
    ('kybernetik-regelkreis', 'p5', '44', 'Kybernetik und Regelkreis', ['Kybernetik', 'Regelkreis', 'Regelung', 'Steuerung', 'Rückkoppelung']),
    ('sollwert-istwert', 'p5', '45', 'Sollwert-Istwert-Regulation', ['Sollwert', 'Istwert', 'Diskrepanz', 'Regulation', 'Homöostase']),
    ('homoeostase', 'p5', '46', 'Homöostase', ['Homöostase', 'Gleichgewicht', 'Fließgleichgewicht', 'Sättigung', 'Regulation']),
    ('rueckkopplung-feedback', 'p5', '47', 'Rückkopplung und Feedback', ['Rückkoppelung', 'Rückkopplung', 'Feedback', 'Regelkreis', 'Signal']),
    ('information-signal', 'p5', '48', 'Information und Signal', ['Information', 'Signal', 'Sender', 'Empfänger', 'Kommunikation']),
    ('adaptation-anpassung', 'p5', '49', 'Adaptation und Anpassung', ['Adaptation', 'Anpassung', 'Umwelt', 'Organismus', 'Reifung']),
    ('evolution-selektion', 'p5', '50', 'Evolution und Selektion', ['Evolution', 'Selektion', 'Phylogenese', 'Instinkt', 'Anpassung']),
    ('instinkt-reflex', 'p5', '51', 'Instinkt und Reflex', ['Instinkt', 'Reflex', 'Reiz', 'Reaktion', 'Ethologie']),
]
NODES = [{"slug": s, "cluster": c, "headings": [h], "title": t, "terms": terms}
         for (s, c, h, t, terms) in _RAW]